{{- range .Values.apps }}
{{- if .createPVC }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
    {{- range .spec.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .spec.resources.requests.storage }}
{{- end }}
{{- end }}
