name: app

image:
  repository: cr.yandex/crp6fd91rf3bhoqildrp/app
  tag: "0.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "20m"
    memory: "32Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

ports:
  - containerPort: 80
    serviceName: http

service:
  type: ClusterIP
  port: 80
